site_name: Kazunya
site_url: https://kazunya.toujoustudios.net/
nav:
  - 'Home': 'index.md'
  - 'Commands':
      - 'All Commands': 'commands/index.md'
      - 'General':
          - '/help': 'commands/general/help.md'
          - '/info': 'commands/general/info.md'
      - 'Roleplay':
          - '/blush': 'commands/roleplay/blush.md'
          - '/cry': 'commands/roleplay/cry.md'
          - '/cuddle': 'commands/roleplay/cuddle.md'
          - '/divorce': 'commands/roleplay/divorce.md'
          - '/fuck': 'commands/roleplay/fuck.md'
          - '/hug': 'commands/roleplay/hug.md'
          - '/kill': 'commands/roleplay/kill.md'
          - '/kiss': 'commands/roleplay/kiss.md'
          - '/laugh': 'commands/roleplay/laugh.md'
          - '/lick': 'commands/roleplay/lick.md'
          - '/marry': 'commands/roleplay/marry.md'
          - '/pat': 'commands/roleplay/pat.md'
          - '/purr': 'commands/roleplay/purr.md'
          - '/smile': 'commands/roleplay/smile.md'
          - '/tickle': 'commands/roleplay/tickle.md'
          - '/bonk': 'commands/roleplay/bonk.md'
          - '/nom': 'commands/roleplay/nom.md'
      - 'Fun':
          - '/pp': 'commands/fun/pp.md'
          - '/roll': 'commands/fun/roll.md'
          - '/ship': 'commands/fun/ship.md'
      - 'Tools':
          - '/avatar': 'commands/tools/avatar.md'
          - '/userinfo': 'commands/tools/userinfo.md'
      - 'Economy':
          - '/wallet': 'commands/economy/wallet.md'
          - '/bank': 'commands/economy/bank.md'
          - '/deposit': 'commands/economy/deposit.md'
          - '/withdraw': 'commands/economy/withdraw.md'
          - '/marketinfo': 'commands/economy/marketinfo.md'
          - '/transfer': 'commands/economy/transfer.md'
  - 'Errors': 'errors/index.md'
  - 'Changelog': 'changelog/index.md'
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
theme:
  name: material
  palette:
    scheme: slate
    primary: pink
